version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - "27018:27017"
    depends_on:
      - mysqldb
    volumes:
      - mongo_data:/data/db

  calculate:
    build: ./CalculationService
    container_name: calculate-container
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_PORT: 27017
    ports:
      - "8086:8086"

  gpa-calculator:
    build: ./GPACalculatorService
    container_name: GPACalculator-container
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - authentication

  authentication:
    build: ./AuthenticationService
    container_name: authentication-service
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - "8082:8082"

  show-results:
    build: ./ShowResultsService
    container_name: show-results-container
    restart: always
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: root
      MONGO_PORT: 27017
    ports:
      - "8090:8090"

volumes:
  mysql_data:
  mongo_data: