version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  gpacalculator:
    build: ./GPACalculatorService
    container_name: GPACalculator-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - authentication

  authentication:
    build: ./AuthenticationService
    container_name: authentication-service
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - "8082:8082"
